# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB" # Better color support for Mac terminal
set -g base-index 1          # Start window numbering at 1
setw -g pane-base-index 1    # Start pane numbering at 1
set -g renumber-windows on   # Renumber when a window is closed
set -g status-position bottom
set -g status-interval 5     # Refresh status line more often

# Prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Better splits
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim-style pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# cycle last-2 sessions
bind o switch-client -l

# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Redraw when change
set-hook -g client-session-changed "refresh-client -S"
set-hook -g session-window-changed "refresh-client -S"
set-hook -g after-select-window "refresh-client -S"
set-hook -g pane-focus-in "refresh-client -S"

# Copy Mode
setw -g mode-keys vi

# Vi-style copy bindings
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"  # macOS
# bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -i"  # Linux

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

bind m run-shell "/Users/parthuu/bin/gs"

# Status Bar
set -g status-position bottom
set -g status-justify centre
set -g status-left-length 20
set -g status-right-length 50

# Default-style status bar
set -g status-style "bg=default,fg=default"

# Left Side (Session)
set -g status-left "#[bold]#{?client_prefix,,#[reverse]} #S #[default] "

# Right Side (Current Directory)
set -g status-right '#[reverse,bold]#(if [ -d .git ]; then echo " $(git branch --show-current)  |"; fi)#(uptime | cut -d"," -f4 | cut -d":" -f2) '

# Tabs / Windows
# Inactive tabs
set -g window-status-format "  #W  "

# Active tab
set -g window-status-current-format "#[bold] -#W  "

# Separator between tabs
set -g window-status-separator "|"

# Optional activity styling
set -g window-status-activity-style "bold"
set -g window-status-bell-style "reverse"

set -g @resurrect-strategy-vim 'session'
# Save and reload sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'

# TPM (always at bottom)
run '~/.tmux/plugins/tpm/tpm'
