# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB" # Better color support for Mac terminal
set -g base-index 1          # Start window numbering at 1
setw -g pane-base-index 1    # Start pane numbering at 1
set -g renumber-windows on   # Renumber when a window is closed
set -g status-position bottom
set -g status-interval 5     # Refresh status line more often

# Prefix
set -g prefix C-s
unbind C-b
bind C-s send-prefix

# Better splits
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload config
bind r source-file ~/.tmux.conf

# Copy Mode
setw -g mode-keys vi

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.3'

# Catppuccin Config
set -g @catppuccin_flavor 'mocha'

# Tabs Config
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_flags "icon"

# Fix for Tab Names & Mauve Active Tab
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# Status Bar Right
set -g status-right-length 100
set -g status-right ""
set -ag status-right "#{E:@catppuccin_status_directory}"

# Status Bar Left
set -g status-left-length 100
set -g status-left "" 
set -ag status-left "#{E:@catppuccin_status_session}"

# Initialize TPM (always at bottom)
run '~/.tmux/plugins/tpm/tpm'
